/**
 * @author Juan Carlos Cancela <cancela.juancarlos@gmail.com>
 */
/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const SET_LOCALE_START = 'SET_LOCALE_START';
export const SET_LOCALE_SUCCESS = 'SET_LOCALE_SUCCESS';
export const SET_LOCALE_ERROR = 'SET_LOCALE_ERROR';
export const FETCH_USERS = 'FETCH_USERS';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_ERROR = 'SEND_EMAIL_ERROR';
export const RESPONSE_END = 'RESPONSE_END';
export const RESPONSE_WAIT = 'RESPONSE_WAIT';
export const AUTH_REFRESH_TOKEN = 'AUTH_REFRESH_TOKEN';
export const FETCH_FACTURAS_SUCCESS = 'FETCH_FACTURAS_SUCCESS';
export const LOCALSTORAGE_AUTH_KEY = 'smg_auth';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const HOST_SERVER = 'http://192.168.104.126/';
export const LOCALHOST_SERVER = 'http://localhost:3000/';
export const TURNOS_SUCCESS = 'TURNOS_SUCCESS';
export const DETALLE_TURNOS_SUCCESS = 'DETALLE_TURNOS_SUCCESS';
export const TURNOS_ERROR = 'TURNOS_ERROR';
export const FETCH_TURNOS_SUCCESS = 'FETCH_TURNOS_SUCCESS';
export const FETCH_DETALLE_TURNOS_SUCCESS = 'FETCH_DETALLE_TURNOS_SUCCESS';
export const FETCH_REMOVE_TURNOS_SUCCESS = 'FETCH_REMOVE_TURNOS_SUCCESS';
export const CLEAN_TURNOS_DELETED = 'CLEAN_TURNOS_DELETED';
export const CLEAN_TURNOS_LIST = 'CLEAN_TURNOS_LIST';
export const FETCH_ESPECIALIDADES_SUCCESS = 'FETCH_ESPECIALIDADES_SUCCESS';
export const FETCH_ESPECIALIDADES_ERROR = 'FETCH_ESPECIALIDADES_ERROR';
export const FETCH_PRACTICAS_SUCCESS = 'FETCH_PRACTICAS_SUCCESS';
export const FETCH_PRACTICAS_ERROR = 'FETCH_PRACTICAS_ERROR';
export const FETCH_CENTROS_SUCCESS = 'FETCH_CENTROS_SUCCESS';
export const FETCH_CENTROS_ERROR = 'FETCH_CENTROS_ERROR';
export const FETCH_PREPARACIONES_SUCCESS = 'FETCH_PREPARACIONES_SUCCESS';
export const FETCH_PREPARACIONES_ERROR = 'FETCH_PREPARACIONES_ERROR';
export const FETCH_PROFESIONALES_SUCCESS = 'FETCH_PROFESIONALES_SUCCESS';
export const FETCH_PROFESIONALES_ERROR = 'FETCH_PROFESIONALES_ERROR';
export const FETCH_PRIMER_FECHA_DISPONIBLE_SUCCESS =
  'FETCH_PRIMER_FECHA_DISPONIBLE_SUCCESS';
export const FETCH_PRIMER_FECHA_DISPONIBLE_ERROR =
  'FETCH_PRIMER_FECHA_DISPONIBLE_ERROR';
export const FETCH_TURNO_POR_FECHA_SUCCESS = 'FETCH_TURNO_POR_FECHA_SUCCESS';
export const FETCH_TURNO_POR_FECHA_ERROR = 'FETCH_TURNO_POR_FECHA_ERROR';
export const FETCH_INTEGRANTES = 'FETCH_INTEGRANTES';
export const FETCH_EMAIL_SUCCESS = 'FETCH_EMAIL_SUCCESS';
export const FETCH_EMAIL_ERROR = 'FETCH_EMAIL_ERROR';
export const FETCH_PHONE_SUCCESS = 'FETCH_PHONE_SUCCESS';
export const FETCH_PHONE_ERROR = 'FETCH_PHONE_ERROR';
export const LOGIN_STATUS_PENDING = 'LOGIN_STATUS_PENDING';
export const LOGIN_STATUS_LOGGED_IN = 'LOGIN_STATUS_LOGGED_IN';
export const LOGIN_STATUS_NOT_LOGGED_IN = 'LOGIN_STATUS_NOT_LOGGED_IN';
export const FETCH_TELEMEDICINA_DISPONIBILIDAD_SUCCESS =
  'FETCH_TELEMEDICINA_DISPONIBILIDAD_SUCCESS';
export const TELEMEDICINA_CLEAN_LIST_SUCCESS =
  'TELEMEDICINA_CLEAN_LIST_SUCCESS';
export const FETCH_TELEMEDICINA_TURNOS_SUCCESS =
  'FETCH_TELEMEDICINA_TURNOS_SUCCESS';
export const DELETE_TELEMEDICINA_TURNOS_SUCCESS =
  'DELETE_TELEMEDICINA_TURNOS_SUCCESS';
export const DETAIL_TELEMEDICINA_TURNOS_SUCCESS =
  'DETAIL_TELEMEDICINA_TURNOS_SUCCESS';
export const SHOW_VALIDACIONES_TECNICAS = 'SHOW_VALIDACIONES_TECNICAS';
export const FETCH_FECHAS_DISPONIBLES_SUCCESS =
  'FETCH_FECHAS_DISPONIBLES_SUCCESS';
export const FETCH_INTEGRANTES_SUCCESS = 'FETCH_INTEGRANTES_SUCCESS';
export const FETCH_INTEGRANTES_ERROR = 'FETCH_INTEGRANTES_ERROR';
export const TELEMEDICINA_INTEGRANTE_SELECCIONADO =
  'TELEMEDICINA_INTEGRANTE_SELECCIONADO';
export const FETCH_TELEMEDICINA_TURNOS_FILTER =
  'FETCH_TELEMEDICINA_TURNOS_FILTER';
export const CLEAN_LIST_ESPECIALIDAD = 'CLEAN_LIST_ESPECIALIDAD';
